// GENERATED by Clients/H-Prime/SEO/build-index-allowlist.py — do not edit by hand.
// Window 2026-06-20 .. 2026-09-17, threshold 10+ impressions over 90 days.
// 24 pages earned the threshold, 0 are kept in for a scheduled
// rewrite, the rest of the list is core routes. Everything outside it renders
// `noindex, follow` and stays out of the sitemaps.

const ALLOWED = new Set<string>([
  '/',
  '/brands/body-craft-repair/services/stationary-bike-repair',
  '/brands/horizon-repair',
  '/brands/nordictrack-repair',
  '/brands/nordictrack-repair/services/stationary-bike-repair',
  '/brands/sole-repair/services/elliptical-repair',
  '/brands/true-fitness-repair',
  '/brands/true-fitness-repair/services/stationary-bike-repair',
  '/cities/castle-pines/services/weight-machine-repair',
  '/cities/castle-rock',
  '/cities/castle-rock/services/spin-bike-repair',
  '/cities/centennial/services/treadmill-repair',
  '/cities/cherry-hills-village/services/stationary-bike-repair',
  '/cities/denver/services/stationary-bike-repair',
  '/cities/greenwood-village/services/weight-machine-repair',
  '/cities/highlands-ranch/services/elliptical-repair',
  '/cities/highlands-ranch/services/rowing-machine-repair',
  '/cities/littleton/services/treadmill-repair',
  '/cities/lone-tree/services/weight-machine-repair',
  '/cities/parker/services/elliptical-repair',
  '/cities/roxborough-park/services/elliptical-repair',
  '/commercial',
  '/parts',
  '/service-areas',
  '/services/elliptical-repair',
  '/services/rowing-machine-repair',
  '/services/spin-bike-repair',
  '/services/stair-machine-repair',
  '/services/stationary-bike-repair',
  '/services/treadmill-repair',
  '/services/weight-machine-repair',
]);

/** True when the path may be indexed and may appear in a sitemap. */
export function isIndexable(pathname: string): boolean {
  const path = pathname.length > 1 ? pathname.replace(/\/+$/, '') : pathname;
  return ALLOWED.has(path || '/');
}

export const allowlistSize = ALLOWED.size;
